// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package api

import (
	"fmt"
	"io"
	"net/url"
	"strconv"
	"time"

	"github.com/oklog/ulid"
)

type AgentAction struct {
	Tool   string `json:"tool"`
	Input  string `json:"input"`
	Output string `json:"output"`
	Denied bool   `json:"denied"`
}

type AgentReply struct {
	Reply   string        `json:"reply"`
	Actions []AgentAction `json:"actions"`
}

type CancelRequestResult struct {
	Success bool `json:"success"`
}

type CancelResponseResult struct {
	Success bool `json:"success"`
}

type ClearHTTPRequestLogResult struct {
	Success bool `json:"success"`
}

type CloseProjectResult struct {
	Success bool `json:"success"`
}

type CreateFindingInput struct {
	Title        string          `json:"title"`
	Description  *string         `json:"description"`
	Severity     FindingSeverity `json:"severity"`
	RequestLogID *ulid.ULID      `json:"requestLogID"`
}

type DeleteFindingResult struct {
	Success bool `json:"success"`
}

type DeleteProjectResult struct {
	Success bool `json:"success"`
}

type DeleteSenderRequestsResult struct {
	Success bool `json:"success"`
}

type DeleteWorkflowResult struct {
	Success bool `json:"success"`
}

type DropWebSocketMessageResult struct {
	Success bool `json:"success"`
}

type Finding struct {
	ID           ulid.ULID       `json:"id"`
	Title        string          `json:"title"`
	Description  string          `json:"description"`
	Severity     FindingSeverity `json:"severity"`
	RequestLogID *ulid.ULID      `json:"requestLogID"`
	Timestamp    time.Time       `json:"timestamp"`
}

type HTTPHeader struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type HTTPHeaderInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type HTTPRequest struct {
	ID       ulid.ULID     `json:"id"`
	URL      *url.URL      `json:"url"`
	Method   HTTPMethod    `json:"method"`
	Proto    HTTPProtocol  `json:"proto"`
	Headers  []HTTPHeader  `json:"headers"`
	Body     *string       `json:"body"`
	Response *HTTPResponse `json:"response"`
}

type HTTPRequestLog struct {
	ID        ulid.ULID        `json:"id"`
	URL       string           `json:"url"`
	Method    HTTPMethod       `json:"method"`
	Proto     string           `json:"proto"`
	Headers   []HTTPHeader     `json:"headers"`
	Body      *string          `json:"body"`
	Timestamp time.Time        `json:"timestamp"`
	Response  *HTTPResponseLog `json:"response"`
}

type HTTPRequestLogFilter struct {
	OnlyInScope      bool    `json:"onlyInScope"`
	SearchExpression *string `json:"searchExpression"`
}

type HTTPRequestLogFilterInput struct {
	OnlyInScope      *bool   `json:"onlyInScope"`
	SearchExpression *string `json:"searchExpression"`
}

type HTTPResponse struct {
	// Will be the same ID as its related request ID.
	ID           ulid.ULID    `json:"id"`
	Proto        HTTPProtocol `json:"proto"`
	StatusCode   int          `json:"statusCode"`
	StatusReason string       `json:"statusReason"`
	Body         *string      `json:"body"`
	Headers      []HTTPHeader `json:"headers"`
}

type HTTPResponseLog struct {
	// Will be the same ID as its related request ID.
	ID           ulid.ULID    `json:"id"`
	Proto        HTTPProtocol `json:"proto"`
	StatusCode   int          `json:"statusCode"`
	StatusReason string       `json:"statusReason"`
	Body         *string      `json:"body"`
	Headers      []HTTPHeader `json:"headers"`
}

type InterceptSettings struct {
	RequestsEnabled  bool    `json:"requestsEnabled"`
	ResponsesEnabled bool    `json:"responsesEnabled"`
	RequestFilter    *string `json:"requestFilter"`
	ResponseFilter   *string `json:"responseFilter"`
}

type InterceptedWebSocketMessage struct {
	ID           ulid.ULID          `json:"id"`
	ConnectionID ulid.ULID          `json:"connectionId"`
	Direction    WebSocketDirection `json:"direction"`
	Opcode       int                `json:"opcode"`
	Payload      string             `json:"payload"`
}

type IntruderAttack struct {
	ID        ulid.ULID            `json:"id"`
	Name      string               `json:"name"`
	Status    IntruderAttackStatus `json:"status"`
	Total     int                  `json:"total"`
	Completed int                  `json:"completed"`
	Timestamp time.Time            `json:"timestamp"`
}

type IntruderHeaderInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type IntruderResult struct {
	Index      int     `json:"index"`
	Payload    string  `json:"payload"`
	StatusCode int     `json:"statusCode"`
	Length     int     `json:"length"`
	DurationMs int     `json:"durationMs"`
	Error      *string `json:"error"`
}

type LLMSettings struct {
	Provider  string `json:"provider"`
	BaseURL   string `json:"baseURL"`
	Model     string `json:"model"`
	HasAPIKey bool   `json:"hasApiKey"`
	Enabled   bool   `json:"enabled"`
}

type LaunchBrowserResult struct {
	Success bool `json:"success"`
}

type MatchReplaceRule struct {
	ID              ulid.ULID         `json:"id"`
	Name            string            `json:"name"`
	Enabled         bool              `json:"enabled"`
	Phase           MatchReplacePhase `json:"phase"`
	Condition       *string           `json:"condition"`
	HeaderName      *string           `json:"headerName"`
	HeaderValue     *string           `json:"headerValue"`
	RemoveHeader    bool              `json:"removeHeader"`
	BodyMatcher     *string           `json:"bodyMatcher"`
	BodyReplacement *string           `json:"bodyReplacement"`
}

type MatchReplaceRuleInput struct {
	Name            string            `json:"name"`
	Enabled         bool              `json:"enabled"`
	Phase           MatchReplacePhase `json:"phase"`
	Condition       *string           `json:"condition"`
	HeaderName      *string           `json:"headerName"`
	HeaderValue     *string           `json:"headerValue"`
	RemoveHeader    *bool             `json:"removeHeader"`
	BodyMatcher     *string           `json:"bodyMatcher"`
	BodyReplacement *string           `json:"bodyReplacement"`
}

type ModifyRequestInput struct {
	ID             ulid.ULID         `json:"id"`
	URL            *url.URL          `json:"url"`
	Method         HTTPMethod        `json:"method"`
	Proto          HTTPProtocol      `json:"proto"`
	Headers        []HTTPHeaderInput `json:"headers"`
	Body           *string           `json:"body"`
	ModifyResponse *bool             `json:"modifyResponse"`
}

type ModifyRequestResult struct {
	Success bool `json:"success"`
}

type ModifyResponseInput struct {
	RequestID    ulid.ULID         `json:"requestID"`
	Proto        HTTPProtocol      `json:"proto"`
	Headers      []HTTPHeaderInput `json:"headers"`
	Body         *string           `json:"body"`
	StatusCode   int               `json:"statusCode"`
	StatusReason string            `json:"statusReason"`
}

type ModifyResponseResult struct {
	Success bool `json:"success"`
}

type ModifyWebSocketMessageInput struct {
	ID      ulid.ULID `json:"id"`
	Payload string    `json:"payload"`
}

type ModifyWebSocketMessageResult struct {
	Success bool `json:"success"`
}

type Project struct {
	ID       ulid.ULID        `json:"id"`
	Name     string           `json:"name"`
	IsActive bool             `json:"isActive"`
	Settings *ProjectSettings `json:"settings"`
}

type ProjectSettings struct {
	Intercept *InterceptSettings `json:"intercept"`
}

type RunAgentInput struct {
	Message string     `json:"message"`
	Mode    *AgentMode `json:"mode"`
}

type SaveWorkflowInput struct {
	ID    *ulid.ULID          `json:"id"`
	Name  string              `json:"name"`
	Steps []WorkflowStepInput `json:"steps"`
}

type ScopeHeader struct {
	Key   *string `json:"key"`
	Value *string `json:"value"`
}

type ScopeHeaderInput struct {
	Key   *string `json:"key"`
	Value *string `json:"value"`
}

type ScopeRule struct {
	URL     *string      `json:"url"`
	Header  *ScopeHeader `json:"header"`
	Body    *string      `json:"body"`
	Exclude bool         `json:"exclude"`
}

type ScopeRuleInput struct {
	URL     *string           `json:"url"`
	Header  *ScopeHeaderInput `json:"header"`
	Body    *string           `json:"body"`
	Exclude *bool             `json:"exclude"`
}

type SenderRequest struct {
	ID                 ulid.ULID        `json:"id"`
	SourceRequestLogID *ulid.ULID       `json:"sourceRequestLogID"`
	URL                *url.URL         `json:"url"`
	Method             HTTPMethod       `json:"method"`
	Proto              HTTPProtocol     `json:"proto"`
	Headers            []HTTPHeader     `json:"headers"`
	Body               *string          `json:"body"`
	Timestamp          time.Time        `json:"timestamp"`
	Response           *HTTPResponseLog `json:"response"`
}

type SenderRequestFilter struct {
	OnlyInScope      bool    `json:"onlyInScope"`
	SearchExpression *string `json:"searchExpression"`
}

type SenderRequestFilterInput struct {
	OnlyInScope      *bool   `json:"onlyInScope"`
	SearchExpression *string `json:"searchExpression"`
}

type SenderRequestInput struct {
	ID      *ulid.ULID        `json:"id"`
	URL     *url.URL          `json:"url"`
	Method  *HTTPMethod       `json:"method"`
	Proto   *HTTPProtocol     `json:"proto"`
	Headers []HTTPHeaderInput `json:"headers"`
	Body    *string           `json:"body"`
}

type SitemapEntry struct {
	Host        string   `json:"host"`
	Path        string   `json:"path"`
	Methods     []string `json:"methods"`
	StatusCodes []int    `json:"statusCodes"`
	Count       int      `json:"count"`
}

type StartIntruderAttackInput struct {
	Name     string                `json:"name"`
	Method   HTTPMethod            `json:"method"`
	URL      string                `json:"url"`
	Headers  []IntruderHeaderInput `json:"headers"`
	Body     *string               `json:"body"`
	Payloads []string              `json:"payloads"`
}

type UpdateInterceptSettingsInput struct {
	RequestsEnabled  bool    `json:"requestsEnabled"`
	ResponsesEnabled bool    `json:"responsesEnabled"`
	RequestFilter    *string `json:"requestFilter"`
	ResponseFilter   *string `json:"responseFilter"`
}

type UpdateLLMSettingsInput struct {
	Provider string `json:"provider"`
	BaseURL  string `json:"baseURL"`
	// When null the stored API key is kept; pass an empty string to clear it.
	APIKey  *string `json:"apiKey"`
	Model   string  `json:"model"`
	Enabled bool    `json:"enabled"`
}

type UpdateWebSocketInterceptSettingsInput struct {
	Enabled bool    `json:"enabled"`
	Filter  *string `json:"filter"`
}

type WebSocketConnection struct {
	ID           ulid.ULID  `json:"id"`
	URL          string     `json:"url"`
	Host         string     `json:"host"`
	Path         string     `json:"path"`
	Timestamp    time.Time  `json:"timestamp"`
	ClosedAt     *time.Time `json:"closedAt"`
	MessageCount int        `json:"messageCount"`
}

type WebSocketInterceptSettings struct {
	Enabled bool    `json:"enabled"`
	Filter  *string `json:"filter"`
}

type WebSocketMessage struct {
	Direction WebSocketDirection `json:"direction"`
	Opcode    int                `json:"opcode"`
	Payload   string             `json:"payload"`
	Timestamp time.Time          `json:"timestamp"`
}

type Workflow struct {
	ID        ulid.ULID      `json:"id"`
	Name      string         `json:"name"`
	Steps     []WorkflowStep `json:"steps"`
	Timestamp time.Time      `json:"timestamp"`
}

type WorkflowStep struct {
	Type        WorkflowStepType `json:"type"`
	Query       *string          `json:"query"`
	Name        *string          `json:"name"`
	Method      *string          `json:"method"`
	URL         *string          `json:"url"`
	Body        *string          `json:"body"`
	Payloads    []string         `json:"payloads"`
	Title       *string          `json:"title"`
	Description *string          `json:"description"`
	Severity    *string          `json:"severity"`
}

type WorkflowStepInput struct {
	Type        WorkflowStepType `json:"type"`
	Query       *string          `json:"query"`
	Name        *string          `json:"name"`
	Method      *string          `json:"method"`
	URL         *string          `json:"url"`
	Body        *string          `json:"body"`
	Payloads    []string         `json:"payloads"`
	Title       *string          `json:"title"`
	Description *string          `json:"description"`
	Severity    *string          `json:"severity"`
}

type WorkflowStepResult struct {
	Type   WorkflowStepType `json:"type"`
	Output string           `json:"output"`
	Error  *string          `json:"error"`
}

type AgentMode string

const (
	AgentModeAsk    AgentMode = "ASK"
	AgentModeAssist AgentMode = "ASSIST"
	AgentModeAuto   AgentMode = "AUTO"
)

var AllAgentMode = []AgentMode{
	AgentModeAsk,
	AgentModeAssist,
	AgentModeAuto,
}

func (e AgentMode) IsValid() bool {
	switch e {
	case AgentModeAsk, AgentModeAssist, AgentModeAuto:
		return true
	}
	return false
}

func (e AgentMode) String() string {
	return string(e)
}

func (e *AgentMode) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AgentMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AgentMode", str)
	}
	return nil
}

func (e AgentMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type FindingSeverity string

const (
	FindingSeverityInfo     FindingSeverity = "INFO"
	FindingSeverityLow      FindingSeverity = "LOW"
	FindingSeverityMedium   FindingSeverity = "MEDIUM"
	FindingSeverityHigh     FindingSeverity = "HIGH"
	FindingSeverityCritical FindingSeverity = "CRITICAL"
)

var AllFindingSeverity = []FindingSeverity{
	FindingSeverityInfo,
	FindingSeverityLow,
	FindingSeverityMedium,
	FindingSeverityHigh,
	FindingSeverityCritical,
}

func (e FindingSeverity) IsValid() bool {
	switch e {
	case FindingSeverityInfo, FindingSeverityLow, FindingSeverityMedium, FindingSeverityHigh, FindingSeverityCritical:
		return true
	}
	return false
}

func (e FindingSeverity) String() string {
	return string(e)
}

func (e *FindingSeverity) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FindingSeverity(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FindingSeverity", str)
	}
	return nil
}

func (e FindingSeverity) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type HTTPMethod string

const (
	HTTPMethodGet     HTTPMethod = "GET"
	HTTPMethodHead    HTTPMethod = "HEAD"
	HTTPMethodPost    HTTPMethod = "POST"
	HTTPMethodPut     HTTPMethod = "PUT"
	HTTPMethodDelete  HTTPMethod = "DELETE"
	HTTPMethodConnect HTTPMethod = "CONNECT"
	HTTPMethodOptions HTTPMethod = "OPTIONS"
	HTTPMethodTrace   HTTPMethod = "TRACE"
	HTTPMethodPatch   HTTPMethod = "PATCH"
)

var AllHTTPMethod = []HTTPMethod{
	HTTPMethodGet,
	HTTPMethodHead,
	HTTPMethodPost,
	HTTPMethodPut,
	HTTPMethodDelete,
	HTTPMethodConnect,
	HTTPMethodOptions,
	HTTPMethodTrace,
	HTTPMethodPatch,
}

func (e HTTPMethod) IsValid() bool {
	switch e {
	case HTTPMethodGet, HTTPMethodHead, HTTPMethodPost, HTTPMethodPut, HTTPMethodDelete, HTTPMethodConnect, HTTPMethodOptions, HTTPMethodTrace, HTTPMethodPatch:
		return true
	}
	return false
}

func (e HTTPMethod) String() string {
	return string(e)
}

func (e *HTTPMethod) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = HTTPMethod(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid HttpMethod", str)
	}
	return nil
}

func (e HTTPMethod) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type HTTPProtocol string

const (
	HTTPProtocolHTTP10 HTTPProtocol = "HTTP10"
	HTTPProtocolHTTP11 HTTPProtocol = "HTTP11"
	HTTPProtocolHTTP20 HTTPProtocol = "HTTP20"
)

var AllHTTPProtocol = []HTTPProtocol{
	HTTPProtocolHTTP10,
	HTTPProtocolHTTP11,
	HTTPProtocolHTTP20,
}

func (e HTTPProtocol) IsValid() bool {
	switch e {
	case HTTPProtocolHTTP10, HTTPProtocolHTTP11, HTTPProtocolHTTP20:
		return true
	}
	return false
}

func (e HTTPProtocol) String() string {
	return string(e)
}

func (e *HTTPProtocol) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = HTTPProtocol(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid HttpProtocol", str)
	}
	return nil
}

func (e HTTPProtocol) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type IntruderAttackStatus string

const (
	IntruderAttackStatusRunning   IntruderAttackStatus = "RUNNING"
	IntruderAttackStatusCompleted IntruderAttackStatus = "COMPLETED"
)

var AllIntruderAttackStatus = []IntruderAttackStatus{
	IntruderAttackStatusRunning,
	IntruderAttackStatusCompleted,
}

func (e IntruderAttackStatus) IsValid() bool {
	switch e {
	case IntruderAttackStatusRunning, IntruderAttackStatusCompleted:
		return true
	}
	return false
}

func (e IntruderAttackStatus) String() string {
	return string(e)
}

func (e *IntruderAttackStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = IntruderAttackStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid IntruderAttackStatus", str)
	}
	return nil
}

func (e IntruderAttackStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type MatchReplacePhase string

const (
	MatchReplacePhaseRequest  MatchReplacePhase = "REQUEST"
	MatchReplacePhaseResponse MatchReplacePhase = "RESPONSE"
)

var AllMatchReplacePhase = []MatchReplacePhase{
	MatchReplacePhaseRequest,
	MatchReplacePhaseResponse,
}

func (e MatchReplacePhase) IsValid() bool {
	switch e {
	case MatchReplacePhaseRequest, MatchReplacePhaseResponse:
		return true
	}
	return false
}

func (e MatchReplacePhase) String() string {
	return string(e)
}

func (e *MatchReplacePhase) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MatchReplacePhase(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MatchReplacePhase", str)
	}
	return nil
}

func (e MatchReplacePhase) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type WebSocketDirection string

const (
	WebSocketDirectionClientToServer WebSocketDirection = "CLIENT_TO_SERVER"
	WebSocketDirectionServerToClient WebSocketDirection = "SERVER_TO_CLIENT"
)

var AllWebSocketDirection = []WebSocketDirection{
	WebSocketDirectionClientToServer,
	WebSocketDirectionServerToClient,
}

func (e WebSocketDirection) IsValid() bool {
	switch e {
	case WebSocketDirectionClientToServer, WebSocketDirectionServerToClient:
		return true
	}
	return false
}

func (e WebSocketDirection) String() string {
	return string(e)
}

func (e *WebSocketDirection) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WebSocketDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WebSocketDirection", str)
	}
	return nil
}

func (e WebSocketDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type WorkflowStepType string

const (
	WorkflowStepTypeSearch  WorkflowStepType = "SEARCH"
	WorkflowStepTypeFuzz    WorkflowStepType = "FUZZ"
	WorkflowStepTypeFinding WorkflowStepType = "FINDING"
)

var AllWorkflowStepType = []WorkflowStepType{
	WorkflowStepTypeSearch,
	WorkflowStepTypeFuzz,
	WorkflowStepTypeFinding,
}

func (e WorkflowStepType) IsValid() bool {
	switch e {
	case WorkflowStepTypeSearch, WorkflowStepTypeFuzz, WorkflowStepTypeFinding:
		return true
	}
	return false
}

func (e WorkflowStepType) String() string {
	return string(e)
}

func (e *WorkflowStepType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkflowStepType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkflowStepType", str)
	}
	return nil
}

func (e WorkflowStepType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
